version: '3.7'
services:
    airflow:
        # image: airflow_image:latest
        build:
            context: airflow_docker/
            dockerfile: Dockerfile
        restart: always
        env_file: .env
        # logging:
        #     options:
        #         max-size: 10m
        #         max-file: "3"
        volumes:
            - ./airflow_docker/logs:/usr/local/airflow/logs
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
    superset:
        # image: superset_image:latest
        build:
            context: superset_docker/
            dockerfile: Dockerfile
        restart: always
        env_file: .env
        # environment:
        #     MAPBOX_API_KEY: ${MAPBOX_API_KEY}
        volumes:
            - ./superset_docker/superset_config.py:/etc/superset/superset_config.py
        ports:
            - "9999:8088"
        # command: ["gunicorn", "superset:app"]
